### ISSUE TITLE
Limit beacon handling if the user stays close to the same beacon

### ISSUE THREAD

**Issue by piuholo** [HSLdevcom/hsl-mobile-app#3]
Power usage could be reduced by limiting the processing of every "beaconsDidRange" event instead of trying to stop the actual ranging.

**Comment by 0is1** [comment]
Some testing related to this: https://github.com/HSLdevcom/hsl-mobile-app/commit/239786db1559103f2029e05c968dde8f77ba1d23

**Comment by 0is1** [comment]
Now in master.

There still might be need for some fine tuning, but Android 6 and 7 phones were up and running over two days (~2d / 2d 15h) when there was active beacons around (from 3 different regions) and the app listened those all that time.

Android 5 phone didn't last more than 23 hours though... but it's possible that the battery is so bad in that particular phone anyways.
